# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'HYSmartPlus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HYSmartPlus
  
  pod 'MJExtension', '~> 3.0.13'
  pod 'MJRefresh', '~> 3.1.15'
  
  pod 'MBProgressHUD', '~> 1.1.0'
  
  pod 'Masonry'
  pod 'SDCycleScrollView','~> 1.66'
  
  pod 'SDWebImage', '~> 4.0.0'
  
  pod 'AFNetworking', '~> 3.1.0'
  pod 'CDDPagerController', '~> 1.1.2'
  
  pod 'DGActivityIndicatorView', '~> 2.1.1'
  
  pod 'TZImagePickerController'
  
  pod 'IQKeyboardManager'
  
  # 主模块(必须)
  pod 'mob_sharesdk'
  
  # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
  pod 'mob_sharesdk/ShareSDKUI'
  
  # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
  pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'   #（微信sdk不带支付的命令）
  
  # 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
  pod 'mob_sharesdk/ShareSDKExtension'
  
end
