# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'HYSmartPlus' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HYSmartPlus
  
  pod 'MJExtension', '~> 3.0.13'
  pod 'MJRefresh', '~> 3.1.15'
  
  pod 'MBProgressHUD', '~> 1.1.0'
  
  pod 'Masonry'
  pod 'SDCycleScrollView','~> 1.66'
  
  pod 'SDWebImage', '~> 4.0.0'
  
  pod 'AFNetworking', '~> 3.1.0'
  pod 'CDDPagerController', '~> 1.1.2'
  
  pod 'DGActivityIndicatorView', '~> 2.1.1'
  
  pod 'TZImagePickerController'
  
  pod 'IQKeyboardManager'

end
